kind: ConfigMap
apiVersion: v1

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}

data: {{ toYaml .Values.config | nindent 2 }}
  url: https://{{ index .Values.ingress.hosts 0 }}
