kind: Deployment
apiVersion: apps/v1

metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    kubernetes.io/change-cause: '{{ .Values.image.tag }}'

spec:
  revisionHistoryLimit: {{ .Values.deployment.revisionHistoryLimit }}

  strategy:
    rollingUpdate:
      maxUnavailable: 1

  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}

  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}

    spec:
      containers:
        - name: default
          image: {{ template "image" . }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
            - secretRef:
                name: {{ .Release.Name }}
          ports:
            - name: h1
              containerPort: 2368
          resources: {{ toYaml .Values.deployment.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: h1
              httpHeaders:
                - name: Host
                  value: {{ index .Values.ingress.hosts 0 }}
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: h1
              httpHeaders:
                - name: Host
                  value: {{ index .Values.ingress.hosts 0 }}
            initialDelaySeconds: 10

      securityContext:
        runAsUser: 1000
        fsGroup: 1000

      imagePullSecrets:
        - name: registry
